version: "3.8"
services:
  angular-app:
    #The docker file in FE, builds and provides the docker image.
    image: azerouhibi/front:latest
    ports:
      - 4200:4200 #Forwars the exposed port 4200 on the container to port 4200 on the host machine
  springboot-be:
    depends_on:
      - mysql-db
    image: azerouhibi/projectdevops:40
    container_name: springboot-be
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql-db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    restart: on-failure
    
volumes:
  db:
